# Generated by Django 6.0.5 on 2026-05-25 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={},
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat.message'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_size',
            field=models.BigIntegerField(),
        ),
    ]
